# Generated by Django 2.1.5 on 2019-03-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('semester_started', models.CharField(blank=True, max_length=30)),
                ('grade_level', models.CharField(blank=True, max_length=30)),
                ('cell_number', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='CoreCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.FloatField(blank=True, max_length=10, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoreCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.CoreCourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.FloatField(blank=True, max_length=10, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.ElectiveCourse')),
            ],
        ),
        migrations.CreateModel(
            name='GradeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MajorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.FloatField(blank=True, max_length=10, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MajorCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.MajorCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=120, null=True)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
            ],
        ),
        migrations.CreateModel(
            name='SecondMajorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.FloatField(blank=True, max_length=10, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecondMajorCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.SecondMajorCourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=100)),
                ('concentration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coursecredit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.MajorCourse'),
        ),
        migrations.AddField(
            model_name='advisee',
            name='first_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisee_first_major', to='advisor.StudyMajor'),
        ),
        migrations.AddField(
            model_name='advisee',
            name='second_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisee_second_major', to='advisor.StudyMajor'),
        ),
    ]
