# Generated by Django 2.1.5 on 2019-02-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.MajorCourse')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.MajorCourse')),
            ],
        ),
        migrations.CreateModel(
            name='MinorCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.MajorCourse')),
            ],
        ),
        migrations.CreateModel(
            name='SecondMajorCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.MajorCourse')),
            ],
        ),
    ]
