# Generated by Django 2.1.5 on 2019-02-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_auto_20190223_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorcoursegrade',
            name='advisee',
        ),
        migrations.RemoveField(
            model_name='minorcoursegrade',
            name='course',
        ),
        migrations.AddField(
            model_name='advisee',
            name='concentration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='MinorCourse',
        ),
        migrations.DeleteModel(
            name='MinorCourseGrade',
        ),
    ]
