# Generated by Django 2.1.5 on 2019-04-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_auto_20190323_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('course_term', models.CharField(blank=True, max_length=10, null=True)),
                ('course_year', models.CharField(blank=True, max_length=10, null=True)),
                ('credits', models.FloatField(blank=True, max_length=10, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_developmental', models.BooleanField(blank=True, default=False)),
                ('advisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisee')),
            ],
        ),
    ]
