# Generated by Django 2.1.5 on 2019-02-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_auto_20190224_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisee',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='is_double_major',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='minor',
        ),
        migrations.AddField(
            model_name='advisee',
            name='second_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_major', to='advisor.StudyMajor'),
        ),
        migrations.AlterField(
            model_name='advisee',
            name='first_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_major', to='advisor.StudyMajor'),
        ),
    ]
