# Generated by Django 2.1.5 on 2019-04-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
