# Generated by Django 2.1.5 on 2019-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0007_advisee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisee',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
