# Generated by Django 2.1.5 on 2019-04-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisor', '0007_auto_20190419_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corecourse',
            name='credits',
            field=models.FloatField(default=3.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='electivecourse',
            name='credits',
            field=models.FloatField(default=3.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secondmajorcourse',
            name='credits',
            field=models.FloatField(default=3.0, max_length=10),
        ),
    ]
