# Generated by Django 2.1.5 on 2019-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_auto_20190420_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
