# Generated by Django 2.1.5 on 2019-04-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0012_auto_20190420_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
